#!/usr/bin/env groovy

// options { buildDiscarder(logRotator(numToKeepStr: '5')) }


node {
    stage('Init Stage'){
        env.APP_NAME = "spr-be"
        env.ACR_NAME = "testrigregistry"
        env.SUBSCRIPTION_ID = "57b13db8-88cf-4fe6-924b-ae10dc6fadee"
        env.AKS_NAME = "demo-aks"
        env.RESOURCE_GROUP = "demo-rg"
	env.BRANCH_NAME = env.BRANCH_NAME.replaceAll('/','_')
    }

    stage('GitCheckout'){
        checkout scm
    }
 
    stage('CreateSeedContainer'){
    withCredentials([azureServicePrincipal('test-rig-demo-jenkins')]) {  
        sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
        sh 'az acr build --file seeder/Dockerfile --subscription  ${SUBSCRIPTION_ID}   --registry ${ACR_NAME} --image ${APP_NAME}:seeder .'
    }}

 
}


 